"""Unit tests for PostgresSourceAdapter cursor-based query generation and execution."""

from __future__ import annotations

from datetime import datetime, timezone
from unittest.mock import MagicMock

import pytest

from src.scd2_copilot.db.models import InventorySourceRow
from src.scd2_copilot.source.adapter import PostgresSourceAdapter
from src.scd2_copilot.source.models import (
    MonitorConfig,
    PostgresSourceDefinition,
    SourceCursor,
)


@pytest.fixture
def mock_db() -> MagicMock:
    db = MagicMock()
    conn = MagicMock()
    cur = MagicMock()
    conn.cursor.return_value.__enter__.return_value = cur
    db.get_connection.return_value.__enter__.return_value = conn
    db.connection.return_value.__enter__.return_value = conn
    return db


@pytest.fixture
def single_key_config() -> MonitorConfig:
    return MonitorConfig(
        name="customers",
        source=PostgresSourceDefinition(table="customers_source"),
        keys=["customer_id"],
        change_timestamp="updated_at",
        tracked_columns=["name", "email", "status"],
    )


@pytest.fixture
def composite_key_config() -> MonitorConfig:
    return MonitorConfig(
        name="inventory",
        source=PostgresSourceDefinition(table="inventory_source"),
        keys=["sku_id", "warehouse_id"],
        change_timestamp="updated_at",
        tracked_columns=["quantity_on_hand", "reorder_level", "status"],
    )


class TestDeriveCursorFromRecord:
    """Tests for derive_cursor_from_record helper."""

    def test_derive_from_dict(self, composite_key_config: MonitorConfig) -> None:
        adapter = PostgresSourceAdapter(config=composite_key_config)
        ts = datetime(2026, 9, 16, 10, 0, 0, tzinfo=timezone.utc)
        record = {
            "sku_id": "SKU-001",
            "warehouse_id": "WH-1",
            "quantity_on_hand": 50,
            "updated_at": ts,
        }
        cursor = adapter.derive_cursor_from_record(record)
        assert cursor.timestamp == ts
        assert cursor.keys == {"sku_id": "SKU-001", "warehouse_id": "WH-1"}
        assert cursor.key_columns == ["sku_id", "warehouse_id"]

    def test_derive_from_model_row(self, composite_key_config: MonitorConfig) -> None:
        adapter = PostgresSourceAdapter(config=composite_key_config)
        ts = datetime(2026, 9, 16, 10, 0, 0, tzinfo=timezone.utc)
        row = InventorySourceRow(
            sku_id="SKU-999",
            warehouse_id="WH-2",
            quantity_on_hand=10,
            reorder_level=5,
            status="active",
            updated_at=ts,
        )
        cursor = adapter.derive_cursor_from_record(row)
        assert cursor.timestamp == ts
        assert cursor.keys == {"sku_id": "SKU-999", "warehouse_id": "WH-2"}


class TestAdapterCursorQueryBuilding:
    """Tests verifying the SQL generated by PostgresSourceAdapter for different cursor states."""

    def test_read_incremental_initial_no_cursor(
        self,
        mock_db: MagicMock,
        single_key_config: MonitorConfig,
    ) -> None:
        adapter = PostgresSourceAdapter(config=single_key_config, db_manager=mock_db)
        cur = mock_db.get_connection.return_value.__enter__.return_value.cursor.return_value.__enter__.return_value
        cur.fetchall.return_value = []

        adapter.read_incremental_records(cursor=None, batch_size=25)

        cur.execute.assert_called_once()
        sql, params = cur.execute.call_args[0]
        sql_str = sql.as_string()
        assert "WHERE" not in sql_str
        assert 'ORDER BY "updated_at" ASC, "customer_id" ASC LIMIT %s' in sql_str
        assert params == [25]

    def test_read_incremental_single_key_cursor(
        self,
        mock_db: MagicMock,
        single_key_config: MonitorConfig,
    ) -> None:
        adapter = PostgresSourceAdapter(config=single_key_config, db_manager=mock_db)
        cur = mock_db.get_connection.return_value.__enter__.return_value.cursor.return_value.__enter__.return_value
        cur.fetchall.return_value = []

        t = datetime(2026, 9, 16, 10, 30, 0, tzinfo=timezone.utc)
        cursor = SourceCursor(timestamp=t, keys={"customer_id": "CUST-42"}, key_columns=["customer_id"])

        adapter.read_incremental_records(cursor=cursor, batch_size=10)

        cur.execute.assert_called_once()
        sql, params = cur.execute.call_args[0]
        sql_str = sql.as_string()
        assert 'WHERE ("updated_at" > %s) OR ("updated_at" = %s AND "customer_id" > %s)' in sql_str
        assert 'ORDER BY "updated_at" ASC, "customer_id" ASC LIMIT %s' in sql_str
        assert params == [t, t, "CUST-42", 10]

    def test_read_incremental_composite_key_cursor(
        self,
        mock_db: MagicMock,
        composite_key_config: MonitorConfig,
    ) -> None:
        adapter = PostgresSourceAdapter(config=composite_key_config, db_manager=mock_db)
        cur = mock_db.get_connection.return_value.__enter__.return_value.cursor.return_value.__enter__.return_value
        cur.fetchall.return_value = []

        t = datetime(2026, 9, 16, 11, 0, 0, tzinfo=timezone.utc)
        cursor = SourceCursor(
            timestamp=t,
            keys={"sku_id": "SKU-100", "warehouse_id": "WH-1"},
            key_columns=["sku_id", "warehouse_id"],
        )

        adapter.read_incremental_records(cursor=cursor, batch_size=5)

        cur.execute.assert_called_once()
        sql, params = cur.execute.call_args[0]
        sql_str = sql.as_string()
        assert 'WHERE ("updated_at" > %s) OR ("updated_at" = %s AND ("sku_id", "warehouse_id") > (%s, %s))' in sql_str
        assert 'ORDER BY "updated_at" ASC, "sku_id" ASC, "warehouse_id" ASC LIMIT %s' in sql_str
        assert params == [t, t, "SKU-100", "WH-1", 5]

    def test_read_incremental_backward_compatibility_watermark_arg(
        self,
        mock_db: MagicMock,
        composite_key_config: MonitorConfig,
    ) -> None:
        adapter = PostgresSourceAdapter(config=composite_key_config, db_manager=mock_db)
        cur = mock_db.get_connection.return_value.__enter__.return_value.cursor.return_value.__enter__.return_value
        cur.fetchall.return_value = []

        t = datetime(2026, 9, 16, 9, 0, 0, tzinfo=timezone.utc)
        # Passing watermark as datetime
        adapter.read_incremental_records(watermark=t, batch_size=50)

        cur.execute.assert_called_once()
        sql, params = cur.execute.call_args[0]
        sql_str = sql.as_string()
        assert 'WHERE "updated_at" > %s' in sql_str
        assert params == [t, 50]
