"""Guided 18-step interactive Demonstration Walkthrough view."""

from __future__ import annotations

from datetime import date, datetime, timezone
import streamlit as st

from ..components import (
    render_ai_advisory_box,
    render_lineage_panel,
    render_metric_card,
    render_onboarding_header,
    render_status_badge,
)
from ..state import AVAILABLE_FIXTURES, OnboardingUIState


DEMO_STEPS_INFO = [
    (1, "Select Customer Dataset", "Ingest raw CRM customer feed, autodetect schema headers and compute SHA-256 raw input fingerprint."),
    (2, "Statistical Data Profiling", "Profile column types, null percentages, distinct counts, and date patterns with privacy-safe PII masking."),
    (3, "AI Semantic Mapping Proposal", "Propose candidate mappings to canonical customer.v1 schema using Gemini/Groq LLM schema reasoning."),
    (4, "Human Review & Approval Gate", "Human data engineer reviews proposed mappings, resolves ambiguities, and seals an immutable mapping version."),
    (5, "Deterministic Transformation & Validation", "Execute native Polars transformation (no eval/exec) and evaluate 4 canonical invariant rules."),
    (6, "Quarantine Invalid Record", "Detect records breaching invariants (e.g. invalid email syntax) and partition away from downstream storage."),
    (7, "Correct & Reprocess Exception", "Operator applies structured value override in Exception Queue and deterministically reprocesses the record."),
    (8, "Durable Run & Idempotency Check", "Submit durable onboarding run, inspect 7-stage lifecycle, and verify X-Idempotent-Replay cached response."),
    (9, "Simulate Source Schema Drift", "Simulate structural schema evolution (added columns, removed fields, type shifts) between source versions."),
    (10, "Mapping Impact & Compatibility Gate", "Evaluate schema drift impact; verify BROKEN status halts downstream ingestion before storage mutation."),
    (11, "Deterministic SCD2 Batch Ingestion", "Feed valid canonical records into core Polars SCD2 engine to compute candidate version validity intervals."),
    (12, "Explore SCD2 History & Point-in-Time", "Query chronological customer history and inspect exact historical state under half-open interval semantics."),
    (13, "Pre-Commit Guardrail Evaluation", "Inspect candidate batch changes prior to database mutation against volumetric and deactivation thresholds."),
    (14, "Simulate Suspicious Mass Deactivation", "A rogue batch deactivates customer records simultaneously, triggering pre-commit guardrail rules."),
    (15, "Verify Zero Historical Mutation", "Verify that target history received 0 writes during hold containment, keeping historical data 100% clean."),
    (16, "Inspect Deterministic Evidence", "Examine frozen evidence and triggered deterministic invariant rules in the containment queue."),
    (17, "Inspect Advisory AI Explanation", "Read the grounded root-cause explanation generated by Gemini/Groq, reinforcing 'AI explains, AI does NOT decide'."),
    (18, "Operator Recovery & History Commit", "Authorized operator reviews evidence, enters justification, and releases held batch to historical storage."),
]


def render_demo_mode_view(state: OnboardingUIState) -> None:
    """Render the guided 18-step interactive demonstration walkthrough screen."""
    render_onboarding_header(
        title="Guided 18-Step Live Demonstration Walkthrough",
        subtitle="Step-by-step interactive journey proving end-to-end data onboarding, canonical validation, schema drift gating, and historical guardrail protection.",
    )

    current_step = st.session_state.get("onb_demo_step", 1)

    # ── Top Demo Control Bar ────────────────────────────────────
    with st.container(border=True):
        c1, c2, c3, c4 = st.columns([1.5, 1, 1, 1])

        with c1:
            step_opts = [f"Step {s[0]}: {s[1]}" for s in DEMO_STEPS_INFO]
            selected_step_str = st.selectbox(
                "Current Demo Step",
                options=step_opts,
                index=current_step - 1,
            )
            selected_idx = int(selected_step_str.split(":")[0].replace("Step", "").strip())
            if selected_idx != current_step:
                st.session_state["onb_demo_step"] = selected_idx
                st.rerun()

        with c2:
            st.markdown("<div style='height: 28px;'></div>", unsafe_allow_html=True)
            if st.button("▶ Run Next Step", type="primary", use_container_width=True):
                _execute_demo_step(state, current_step)
                if current_step < len(DEMO_STEPS_INFO):
                    st.session_state["onb_demo_step"] = current_step + 1
                st.rerun()

        with c3:
            st.markdown("<div style='height: 28px;'></div>", unsafe_allow_html=True)
            if st.button("⚡ Run Full Flow", type="secondary", use_container_width=True):
                with st.spinner("Executing all 18 demonstration steps sequentially..."):
                    for s_num in range(1, len(DEMO_STEPS_INFO) + 1):
                        _execute_demo_step(state, s_num)
                    st.session_state["onb_demo_step"] = len(DEMO_STEPS_INFO)
                st.success("🎉 Complete 18-Step Golden Demo executed successfully!")
                st.rerun()

        with c4:
            st.markdown("<div style='height: 28px;'></div>", unsafe_allow_html=True)
            if st.button("🔄 Reset Demo", type="secondary", use_container_width=True):
                st.session_state["onb_demo_step"] = 1
                st.session_state["onb_raw_df"] = None
                st.session_state["onb_profile"] = None
                st.session_state["onb_proposals"] = None
                st.session_state["onb_approved_mapping"] = None
                st.session_state["onb_transformation_result"] = None
                st.session_state["onb_exception_batch"] = None
                st.session_state["onb_drift_report"] = None
                st.session_state["onb_scd2_result"] = None
                st.session_state["onb_guardrail_result"] = None
                st.info("Demo state reset to Step 1.")
                st.rerun()

    st.markdown("<div style='height: 12px;'></div>", unsafe_allow_html=True)

    # ── Active Step Card ────────────────────────────────────────
    step_num, step_title, step_desc = DEMO_STEPS_INFO[current_step - 1]

    st.markdown(
        f"""
        <div style="background: #ffffff; border: 1px solid #cbd5e1; border-radius: 12px; padding: 20px 24px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); margin-bottom: 20px;">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                <span class="onb-badge onb-badge-info">STEP {step_num} OF 18</span>
                <span style="font-size: 0.85rem; color: #64748b; font-weight: 600;">Automated Execution Ready</span>
            </div>
            <div style="font-size: 1.35rem; font-weight: 800; color: #0f172a; line-height: 1.25;">
                {step_title}
            </div>
            <div style="font-size: 0.92rem; color: #475569; margin-top: 6px; line-height: 1.5;">
                {step_desc}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # ── Render Dynamic Step Output ──────────────────────────────
    _render_step_details(state, current_step)


def _execute_demo_step(state: OnboardingUIState, step: int) -> None:
    """Execute the domain service logic for a specific demo step."""
    if step == 1:
        state.load_fixture("CRM Customers")
    elif step == 2:
        state.profile_active_source()
    elif step == 3:
        state.generate_mapping_proposals(enable_ai=True)
    elif step == 4:
        state.approve_all_mappings()
    elif step == 5 or step == 6:
        state.run_transformation()
    elif step == 7:
        batch = st.session_state.get("onb_exception_batch")
        if batch and batch.exceptions:
            state.correct_and_reprocess(
                exception=batch.exceptions[0],
                field_name=batch.exceptions[0].field,
                corrected_value="fixed.customer@enterprise.org",
                reason="Manual operator correction verified during demo",
            )
    elif step == 8:
        state.submit_durable_run()
    elif step == 9 or step == 10:
        state.evaluate_schema_drift()
    elif step == 11 or step == 12:
        state.process_scd2_normal_batch()
    elif step == 13 or step == 14 or step == 15 or step == 16 or step == 17:
        state.trigger_suspicious_hold()
    elif step == 18:
        holds = state.list_holds()
        active = [h for h in holds if h.status == "HELD"]
        if active:
            state.release_held_batch(active[0].hold_id, reason="Demo operator authorized seasonal update.")


def _render_step_details(state: OnboardingUIState, step: int) -> None:
    """Render the contextual proof and live state for the active demo step."""
    if step == 1:
        df = st.session_state.get("onb_raw_df")
        schema = st.session_state.get("onb_source_schema")
        if df is None:
            df, schema = state.load_fixture("CRM Customers")
        st.markdown(f"**Loaded Fixture:** `{st.session_state.get('onb_selected_fixture')}` ({df.height} records, {len(schema.columns)} columns)")
        st.dataframe(df.head(5), use_container_width=True)
        render_lineage_panel(source_id="crm_salesforce", schema_fingerprint=schema.schema_fingerprint)

    elif step == 2:
        profile = st.session_state.get("onb_profile")
        if profile is None:
            profile = state.profile_active_source()
        st.markdown(f"**Profile Summary:** `{profile.total_rows}` rows profiled across `{len(profile.columns)}` columns.")
        prof_summary = [{"Column": c.column_name, "Inferred Type": c.inferred_type, "Null %": f"{c.null_percentage:.1f}%", "Uniqueness": f"{c.uniqueness_ratio * 100:.1f}%"} for c in profile.columns]
        st.dataframe(prof_summary, use_container_width=True)

    elif step == 3:
        proposals = st.session_state.get("onb_proposals")
        if proposals is None:
            proposals = state.generate_mapping_proposals()
        st.markdown(f"**Proposed Mappings:** `{len(proposals.proposals)}` field candidates generated.")
        prop_data = [{"Source": p.source_field, "Canonical Target": p.target_field or "—", "Type": p.mapping_type.value, "Confidence": f"{p.confidence * 100:.0f}%"} for p in proposals.proposals]
        st.dataframe(prop_data, use_container_width=True)
        if proposals.explanation:
            render_ai_advisory_box(proposals.explanation)

    elif step == 4:
        approved = st.session_state.get("onb_approved_mapping")
        if approved is None:
            approved = state.approve_all_mappings()
        st.success(f"Mapping Version **v{approved.version_number}** sealed and cryptographically hashed! Content Hash: `{approved.source_fingerprint[:16]}...`")
        render_lineage_panel(mapping_version=approved.mapping_version_id, schema_fingerprint=approved.source_fingerprint)

    elif step == 5 or step == 6:
        res = st.session_state.get("onb_transformation_result")
        if res is None:
            res = state.run_transformation()
        c1, c2 = st.columns(2)
        c1.metric("Valid Canonical Records", res.valid_record_count)
        c2.metric("Invalid Quarantined Records", res.invalid_record_count)
        if res.invalid_records:
            st.warning(f"Quarantined {res.invalid_record_count} records breaching canonical contract rules:")
            errs = [
                {
                    "Record ID": inv.source_record_id or f"row_{inv.row_index}",
                    "Rule": e.rule_id,
                    "Reason": e.reason,
                }
                for inv in res.invalid_records
                for e in inv.errors
            ]
            st.dataframe(errs, use_container_width=True)

    elif step == 7:
        batch = st.session_state.get("onb_exception_batch")
        if batch and batch.exceptions:
            st.info(f"Exception `{batch.exceptions[0].exception_id}` was corrected and reprocessed:")
            st.markdown(f"• **Status:** {batch.exceptions[0].status.value}\n• **History:** {len(batch.exceptions[0].corrections)} corrections recorded.")

    elif step == 8:
        run = state.get_latest_run()
        if run:
            st.success(f"Durable Run `{run.run_id}` recorded with status: **{run.status.value}**")
            render_lineage_panel(run_id=run.run_id, source_id=run.source_id, mapping_version=run.mapping_version_id, input_fingerprint=run.input_fingerprint)

    elif step == 9 or step == 10:
        drift = st.session_state.get("onb_drift_report")
        if drift is None:
            drift = state.evaluate_schema_drift()
        st.markdown(f"**Schema Drift Compatibility:** `{drift.overall_compatibility.value}` ({len(drift.drift_events)} drift events detected)")
        diff_data = [{"Event": e.drift_type.value, "Column": e.field_name, "Prior": e.old_type or "—", "Current": e.new_type or "—"} for e in drift.drift_events]
        st.dataframe(diff_data, use_container_width=True)

    elif step == 11 or step == 12:
        hist = state.scd2_service.get_customer_history("CUST-1001")
        st.markdown(f"**SCD2 History for `CUST-1001`:** `{len(hist)}` chronological versions recorded.")
        t_data = [{"History ID": str(h.history_id)[:8], "Effective From": str(h.effective_from)[:19], "Effective To": str(h.effective_to)[:19] if h.effective_to else "NULL (Active)", "Current": h.is_current} for h in hist]
        st.dataframe(t_data, use_container_width=True)

    elif step in (13, 14, 15, 16, 17):
        holds = state.list_holds()
        active = [h for h in holds if h.status == "HELD"]
        if active:
            h = active[0]
            rules = h.evidence.get("triggered_rules", []) if isinstance(h.evidence, dict) else []
            st.error(f"🚨 **SUSPICIOUS BATCH HELD:** `{h.hold_id}` (Severity: {h.severity})\n\nTriggered Rules: `{rules}`")
            st.markdown(
                """
                <div style="background: #f0fdf4; border: 1px solid #86efac; border-radius: 8px; padding: 12px 16px; margin: 10px 0;">
                    <strong>Historical Immutability Verified:</strong> Target table <code>monitored_entity_history</code> received <strong>0 writes</strong>. History is 100% untouched.
                </div>
                """,
                unsafe_allow_html=True,
            )
            ai_expl = h.evidence.get("ai_explanation") if isinstance(h.evidence, dict) else None
            if ai_expl:
                render_ai_advisory_box(ai_expl)

    elif step == 18:
        holds = state.list_holds()
        released = [h for h in holds if h.status == "RELEASED"]
        if released:
            st.success(f"Hold `{released[0].hold_id}` successfully **RELEASED** by operator! Records committed to history.")
        else:
            st.info("Click 'Run Next Step' to authorize and release the held batch to historical storage.")
