"""Onboarding contracts and domain models."""

from .source import SourceDefinition, SourceType
from .schema_snapshot import ColumnSnapshot, SchemaFingerprint, SourceSchemaSnapshot
from .profile import (
    ColumnProfile,
    DataProfile,
    DatePatternReport,
    SamplingConfig,
    SamplingPolicy,
    ValueFrequency,
)
from .mapping import (
    CandidateMapping,
    DeterministicEvidence,
    FieldMappingProposal,
    LLMFieldProposal,
    LLMMappingBatchResponse,
    MappingProposalBatch,
    MappingType,
    TransformationOpType,
    TransformationStep,
)
from .approval import (
    ApprovedMappingDefinition,
    ApprovedMappingVersion,
    FieldReviewDecision,
    ReviewDecisionType,
)
from .transformation import (
    CanonicalCustomerRecord,
    RecordValidationError,
    TransformationResult,
    TransformedRecord,
    ValidationCategory,
    ValidationErrorSeverity,
)
from .exception import (
    CorrectionType,
    CustomerRecordException,
    DEFAULT_NON_DISMISSIBLE_RULES,
    ExceptionBatch,
    ExceptionCategory,
    ExceptionStatus,
    RecordCorrection,
    ReprocessingResult,
)
from .run import (
    OnboardingRun,
    RunArtifactPaths,
    RunCancelRequest,
    RunCreateRequest,
    RunListResponse,
    RunMetrics,
    RunResponse,
    RunRetryRequest,
    RunStatus,
    VALID_RUN_TRANSITIONS,
    validate_run_transition,
)
from .drift import (
    DriftType,
    FieldMappingImpact,
    MappingCompatibilityState,
    SchemaDiffResult,
    SchemaDriftEvent,
    SchemaDriftReport,
)

__all__ = [
    "SourceDefinition",
    "SourceType",
    "ColumnSnapshot",
    "SchemaFingerprint",
    "SourceSchemaSnapshot",
    "ColumnProfile",
    "DataProfile",
    "DatePatternReport",
    "SamplingConfig",
    "SamplingPolicy",
    "ValueFrequency",
    "TransformationOpType",
    "TransformationStep",
    "MappingType",
    "DeterministicEvidence",
    "CandidateMapping",
    "FieldMappingProposal",
    "MappingProposalBatch",
    "LLMFieldProposal",
    "LLMMappingBatchResponse",
    "ReviewDecisionType",
    "FieldReviewDecision",
    "ApprovedMappingDefinition",
    "ApprovedMappingVersion",
    "ValidationCategory",
    "ValidationErrorSeverity",
    "RecordValidationError",
    "CanonicalCustomerRecord",
    "TransformedRecord",
    "TransformationResult",
    "ExceptionCategory",
    "ExceptionStatus",
    "CorrectionType",
    "RecordCorrection",
    "ReprocessingResult",
    "DEFAULT_NON_DISMISSIBLE_RULES",
    "CustomerRecordException",
    "ExceptionBatch",
    "RunStatus",
    "VALID_RUN_TRANSITIONS",
    "validate_run_transition",
    "RunMetrics",
    "RunArtifactPaths",
    "OnboardingRun",
    "RunCreateRequest",
    "RunResponse",
    "RunListResponse",
    "RunRetryRequest",
    "RunCancelRequest",
    "DriftType",
    "MappingCompatibilityState",
    "SchemaDriftEvent",
    "FieldMappingImpact",
    "SchemaDiffResult",
    "SchemaDriftReport",
]



